//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkDownEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkDownEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelException.
        /// </summary>
        internal static string CancelException {
            get {
                return ResourceManager.GetString("CancelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Text Area.
        /// </summary>
        internal static string EmptyBoldAreaText {
            get {
                return ResourceManager.GetString("EmptyBoldAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string EmptyCode {
            get {
                return ResourceManager.GetString("EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the link.
        /// </summary>
        internal static string EmptyHyperlinkDescription {
            get {
                return ResourceManager.GetString("EmptyHyperlinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the image.
        /// </summary>
        internal static string EmptyImageDescription {
            get {
                return ResourceManager.GetString("EmptyImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic Text Area.
        /// </summary>
        internal static string EmptyItalicAreaText {
            get {
                return ResourceManager.GetString("EmptyItalicAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Item.
        /// </summary>
        internal static string ListItem {
            get {
                return ResourceManager.GetString("ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Documents|*.md;*.markdown|All Files|*.*.
        /// </summary>
        internal static string MarkDownFileFilter {
            get {
                return ResourceManager.GetString("MarkDownFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word|*.docx.
        /// </summary>
        internal static string TypeDocxFilter {
            get {
                return ResourceManager.GetString("TypeDocxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word 2007-2016 Document Format.
        /// </summary>
        internal static string TypeDocxToolTip {
            get {
                return ResourceManager.GetString("TypeDocxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Publication|*.epub.
        /// </summary>
        internal static string TypeEpubFilter {
            get {
                return ResourceManager.GetString("TypeEpubFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Publication Format.
        /// </summary>
        internal static string TypeEpubToolTip {
            get {
                return ResourceManager.GetString("TypeEpubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Web Page|*.html.
        /// </summary>
        internal static string TypeHtmlFilter {
            get {
                return ResourceManager.GetString("TypeHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperText Markup Language.
        /// </summary>
        internal static string TypeHtmlToolTip {
            get {
                return ResourceManager.GetString("TypeHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEX Document|*.tex.
        /// </summary>
        internal static string TypeLatexFilter {
            get {
                return ResourceManager.GetString("TypeLatexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest to compile exported tex files using XeLatex command if CJK characters exist in document.
        /// </summary>
        internal static string TypeLatexToolTip {
            get {
                return ResourceManager.GetString("TypeLatexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain HTML Web Page|*.html.
        /// </summary>
        internal static string TypePlainHtmlFilter {
            get {
                return ResourceManager.GetString("TypePlainHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperText Markup Language without any css.
        /// </summary>
        internal static string TypePlainHtmlToolTip {
            get {
                return ResourceManager.GetString("TypePlainHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format|*.rtf.
        /// </summary>
        internal static string TypeRTFFilter {
            get {
                return ResourceManager.GetString("TypeRTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format.
        /// </summary>
        internal static string TypeRTFTip {
            get {
                return ResourceManager.GetString("TypeRTFTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string UntitledTitle {
            get {
                return ResourceManager.GetString("UntitledTitle", resourceCulture);
            }
        }
    }
}
