//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkDownEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkDownEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CancelException 的本地化字符串。
        /// </summary>
        internal static string CancelException {
            get {
                return ResourceManager.GetString("CancelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold Text Area 的本地化字符串。
        /// </summary>
        internal static string EmptyBoldAreaText {
            get {
                return ResourceManager.GetString("EmptyBoldAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        internal static string EmptyCode {
            get {
                return ResourceManager.GetString("EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description of the link 的本地化字符串。
        /// </summary>
        internal static string EmptyHyperlinkDescription {
            get {
                return ResourceManager.GetString("EmptyHyperlinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description of the image 的本地化字符串。
        /// </summary>
        internal static string EmptyImageDescription {
            get {
                return ResourceManager.GetString("EmptyImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic Text Area 的本地化字符串。
        /// </summary>
        internal static string EmptyItalicAreaText {
            get {
                return ResourceManager.GetString("EmptyItalicAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List Item 的本地化字符串。
        /// </summary>
        internal static string ListItem {
            get {
                return ResourceManager.GetString("ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Markdown Documents|*.md;*.markdown|All Files|*.* 的本地化字符串。
        /// </summary>
        internal static string MarkDownFileFilter {
            get {
                return ResourceManager.GetString("MarkDownFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Word|*.docx 的本地化字符串。
        /// </summary>
        internal static string TypeDocxFilter {
            get {
                return ResourceManager.GetString("TypeDocxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Word 2007-2016 Document Format 的本地化字符串。
        /// </summary>
        internal static string TypeDocxToolTip {
            get {
                return ResourceManager.GetString("TypeDocxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Electronic Publication|*.epub 的本地化字符串。
        /// </summary>
        internal static string TypeEpubFilter {
            get {
                return ResourceManager.GetString("TypeEpubFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Electronic Publication Format 的本地化字符串。
        /// </summary>
        internal static string TypeEpubToolTip {
            get {
                return ResourceManager.GetString("TypeEpubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML Web Page|*.html 的本地化字符串。
        /// </summary>
        internal static string TypeHtmlFilter {
            get {
                return ResourceManager.GetString("TypeHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HyperText Markup Language 的本地化字符串。
        /// </summary>
        internal static string TypeHtmlToolTip {
            get {
                return ResourceManager.GetString("TypeHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LATEX Document|*.tex 的本地化字符串。
        /// </summary>
        internal static string TypeLatexFilter {
            get {
                return ResourceManager.GetString("TypeLatexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We suggest to compile exported tex files using XeLatex command if CJK characters exist in document 的本地化字符串。
        /// </summary>
        internal static string TypeLatexToolTip {
            get {
                return ResourceManager.GetString("TypeLatexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portable Document Format|*.pdf 的本地化字符串。
        /// </summary>
        internal static string TypePdfFilter {
            get {
                return ResourceManager.GetString("TypePdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portable Document Format 的本地化字符串。
        /// </summary>
        internal static string TypePdfToolTip {
            get {
                return ResourceManager.GetString("TypePdfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plain HTML Web Page|*.html 的本地化字符串。
        /// </summary>
        internal static string TypePlainHtmlFilter {
            get {
                return ResourceManager.GetString("TypePlainHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HyperText Markup Language without any css 的本地化字符串。
        /// </summary>
        internal static string TypePlainHtmlToolTip {
            get {
                return ResourceManager.GetString("TypePlainHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rich Text Format|*.rtf 的本地化字符串。
        /// </summary>
        internal static string TypeRTFFilter {
            get {
                return ResourceManager.GetString("TypeRTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rich Text Format 的本地化字符串。
        /// </summary>
        internal static string TypeRTFTip {
            get {
                return ResourceManager.GetString("TypeRTFTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        internal static string UntitledTitle {
            get {
                return ResourceManager.GetString("UntitledTitle", resourceCulture);
            }
        }
    }
}
