//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkDownEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkDownEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom css files.
        /// </summary>
        public static string AddCustomCSS {
            get {
                return ResourceManager.GetString("AddCustomCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold (Ctrl+B).
        /// </summary>
        public static string BoldCommand {
            get {
                return ResourceManager.GetString("BoldCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code (Ctrl+K).
        /// </summary>
        public static string CodeCommand {
            get {
                return ResourceManager.GetString("CodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        public static string Col {
            get {
                return ResourceManager.GetString("Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy your custom css file into the following folder. It&apos;ll take effect after restart..
        /// </summary>
        public static string CopyCSS {
            get {
                return ResourceManager.GetString("CopyCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Stamp (Ctrl++Shift+D).
        /// </summary>
        public static string DateStampCommand {
            get {
                return ResourceManager.GetString("DateStampCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t remind for this update!.
        /// </summary>
        public static string DoNotRemindForThisUpdate {
            get {
                return ResourceManager.GetString("DoNotRemindForThisUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string DoNotSave {
            get {
                return ResourceManager.GetString("DoNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Text Area.
        /// </summary>
        public static string EmptyBoldAreaText {
            get {
                return ResourceManager.GetString("EmptyBoldAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string EmptyCode {
            get {
                return ResourceManager.GetString("EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the link.
        /// </summary>
        public static string EmptyHyperlinkDescription {
            get {
                return ResourceManager.GetString("EmptyHyperlinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the image.
        /// </summary>
        public static string EmptyImageDescription {
            get {
                return ResourceManager.GetString("EmptyImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic Text Area.
        /// </summary>
        public static string EmptyItalicAreaText {
            get {
                return ResourceManager.GetString("EmptyItalicAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t be exported in this version!.
        /// </summary>
        public static string Error_ExportError {
            get {
                return ResourceManager.GetString("Error_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To.
        /// </summary>
        public static string ExportTo {
            get {
                return ResourceManager.GetString("ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export.
        /// </summary>
        public static string FailedToExport {
            get {
                return ResourceManager.GetString("FailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string FindPrevious {
            get {
                return ResourceManager.GetString("FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; Replace.
        /// </summary>
        public static string FindReplace {
            get {
                return ResourceManager.GetString("FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Current Line.
        /// </summary>
        public static string HighlightCurrentLine {
            get {
                return ResourceManager.GetString("HighlightCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Rule (Ctrl+R).
        /// </summary>
        public static string HorizontalRuleCommand {
            get {
                return ResourceManager.GetString("HorizontalRuleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink (Ctrl+L).
        /// </summary>
        public static string HyperlinkCommand {
            get {
                return ResourceManager.GetString("HyperlinkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image (Ctrl+G).
        /// </summary>
        public static string ImageCommand {
            get {
                return ResourceManager.GetString("ImageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images|*.bmp;*.jpg;*.gif;*.png;*.tif.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of file is larger than 10MB, unable to upload!.
        /// </summary>
        public static string ImageSizeError {
            get {
                return ResourceManager.GetString("ImageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an image URL.
        /// </summary>
        public static string InputImage {
            get {
                return ResourceManager.GetString("InputImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an URL.
        /// </summary>
        public static string InputLink {
            get {
                return ResourceManager.GetString("InputLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert local image URL.
        /// </summary>
        public static string InsertLocalImage {
            get {
                return ResourceManager.GetString("InsertLocalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Settings.
        /// </summary>
        public static string InternationalSettings {
            get {
                return ResourceManager.GetString("InternationalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic (Ctrl+I).
        /// </summary>
        public static string ItalicCommand {
            get {
                return ResourceManager.GetString("ItalicCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language will be switched after restart.
        /// </summary>
        public static string LanguageSwitch {
            get {
                return ResourceManager.GetString("LanguageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Item.
        /// </summary>
        public static string ListItem {
            get {
                return ResourceManager.GetString("ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        public static string Ln {
            get {
                return ResourceManager.GetString("Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Documents|*.md;*.markdown|All Files|*.*.
        /// </summary>
        public static string MarkDownFileFilter {
            get {
                return ResourceManager.GetString("MarkDownFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string MatchWholeWord {
            get {
                return ResourceManager.GetString("MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New (Ctrl+N).
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document Created.
        /// </summary>
        public static string NewDocumentCreated {
            get {
                return ResourceManager.GetString("NewDocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is released!.
        /// </summary>
        public static string NewVersionIsReleased {
            get {
                return ResourceManager.GetString("NewVersionIsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Mode.
        /// </summary>
        public static string NightMode {
            get {
                return ResourceManager.GetString("NightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CSS.
        /// </summary>
        public static string NoCSS {
            get {
                return ResourceManager.GetString("NoCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Image Storage Service.
        /// </summary>
        public static string OISS {
            get {
                return ResourceManager.GetString("OISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Image.
        /// </summary>
        public static string OnlineImage {
            get {
                return ResourceManager.GetString("OnlineImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In External Browser (F6).
        /// </summary>
        public static string Open_In_External_Browser {
            get {
                return ResourceManager.GetString("Open_In_External_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open (Ctrl+O).
        /// </summary>
        public static string OpenCommand {
            get {
                return ResourceManager.GetString("OpenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opened successfully.
        /// </summary>
        public static string OpenedSuccessfully {
            get {
                return ResourceManager.GetString("OpenedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file failed!.
        /// </summary>
        public static string OpenFileFailed {
            get {
                return ResourceManager.GetString("OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Right Now.
        /// </summary>
        public static string OpenRightNow {
            get {
                return ResourceManager.GetString("OpenRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open This Folder.
        /// </summary>
        public static string OpenThisFolder {
            get {
                return ResourceManager.GetString("OpenThisFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Title.
        /// </summary>
        public static string OptionalTitle {
            get {
                return ResourceManager.GetString("OptionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered List (Ctrl+Shift+O).
        /// </summary>
        public static string OrderedListCommand {
            get {
                return ResourceManager.GetString("OrderedListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QiniuConf.
        /// </summary>
        public static string QiniuConf {
            get {
                return ResourceManager.GetString("QiniuConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QiniuUserDomainName.
        /// </summary>
        public static string QiniuUserDomainName {
            get {
                return ResourceManager.GetString("QiniuUserDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QiniuUserScope.
        /// </summary>
        public static string QiniuUserScope {
            get {
                return ResourceManager.GetString("QiniuUserScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote (Ctrl+Q).
        /// </summary>
        public static string QuoteCommand {
            get {
                return ResourceManager.GetString("QuoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Mode/Preview Mode.
        /// </summary>
        public static string Reading_Preview_Mode {
            get {
                return ResourceManager.GetString("Reading_Preview_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        public static string RefreshCommand {
            get {
                return ResourceManager.GetString("RefreshCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Completed!.
        /// </summary>
        public static string ReplaceCompleted {
            get {
                return ResourceManager.GetString("ReplaceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruler.
        /// </summary>
        public static string Ruler {
            get {
                return ResourceManager.GetString("Ruler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruler Position.
        /// </summary>
        public static string RulerPosition {
            get {
                return ResourceManager.GetString("RulerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As (Ctrl+Shift+S).
        /// </summary>
        public static string SaveAsCommand {
            get {
                return ResourceManager.GetString("SaveAsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        public static string SaveCommand {
            get {
                return ResourceManager.GetString("SaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file failed!.
        /// </summary>
        public static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollbar Synchronization.
        /// </summary>
        public static string Scrollbar_Synchronization {
            get {
                return ResourceManager.GetString("Scrollbar_Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image Type.
        /// </summary>
        public static string SelectImageType {
            get {
                return ResourceManager.GetString("SelectImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column Ruler.
        /// </summary>
        public static string ShowColumnRuler {
            get {
                return ResourceManager.GetString("ShowColumnRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show End Of Line.
        /// </summary>
        public static string ShowEndOfLine {
            get {
                return ResourceManager.GetString("ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Line Numbers.
        /// </summary>
        public static string ShowLineNumbers {
            get {
                return ResourceManager.GetString("ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MathJax.
        /// </summary>
        public static string ShowMathJax {
            get {
                return ResourceManager.GetString("ShowMathJax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Preview.
        /// </summary>
        public static string ShowPreview {
            get {
                return ResourceManager.GetString("ShowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Spaces.
        /// </summary>
        public static string ShowSpaces {
            get {
                return ResourceManager.GetString("ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tabs.
        /// </summary>
        public static string ShowTabs {
            get {
                return ResourceManager.GetString("ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Exported.
        /// </summary>
        public static string SuccessfullyExported {
            get {
                return ResourceManager.GetString("SuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp (Ctrl+T).
        /// </summary>
        public static string TimeStampCommand {
            get {
                return ResourceManager.GetString("TimeStampCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading (Ctrl+H).
        /// </summary>
        public static string TitleCommand {
            get {
                return ResourceManager.GetString("TitleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word|*.docx.
        /// </summary>
        public static string TypeDocxFilter {
            get {
                return ResourceManager.GetString("TypeDocxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word 2007-2016 Document Format.
        /// </summary>
        public static string TypeDocxToolTip {
            get {
                return ResourceManager.GetString("TypeDocxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Publication|*.epub.
        /// </summary>
        public static string TypeEpubFilter {
            get {
                return ResourceManager.GetString("TypeEpubFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Publication Format.
        /// </summary>
        public static string TypeEpubToolTip {
            get {
                return ResourceManager.GetString("TypeEpubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Web Page|*.html.
        /// </summary>
        public static string TypeHtmlFilter {
            get {
                return ResourceManager.GetString("TypeHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperText Markup Language.
        /// </summary>
        public static string TypeHtmlToolTip {
            get {
                return ResourceManager.GetString("TypeHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG|*.jpg|PNG|*.png.
        /// </summary>
        public static string TypeImageFilter {
            get {
                return ResourceManager.GetString("TypeImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string TypeImageToolTip {
            get {
                return ResourceManager.GetString("TypeImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEX Document|*.tex.
        /// </summary>
        public static string TypeLatexFilter {
            get {
                return ResourceManager.GetString("TypeLatexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest to compile exported tex files using XeLatex command if CJK characters exist in document.
        /// </summary>
        public static string TypeLatexToolTip {
            get {
                return ResourceManager.GetString("TypeLatexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Document Format|*.pdf.
        /// </summary>
        public static string TypePdfFilter {
            get {
                return ResourceManager.GetString("TypePdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Document Format.
        /// </summary>
        public static string TypePdfToolTip {
            get {
                return ResourceManager.GetString("TypePdfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain HTML Web Page|*.html.
        /// </summary>
        public static string TypePlainHtmlFilter {
            get {
                return ResourceManager.GetString("TypePlainHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperText Markup Language without any css.
        /// </summary>
        public static string TypePlainHtmlToolTip {
            get {
                return ResourceManager.GetString("TypePlainHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format|*.rtf.
        /// </summary>
        public static string TypeRTFFilter {
            get {
                return ResourceManager.GetString("TypeRTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format.
        /// </summary>
        public static string TypeRTFTip {
            get {
                return ResourceManager.GetString("TypeRTFTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unordered List (Ctrl+U).
        /// </summary>
        public static string UnorderedListCommand {
            get {
                return ResourceManager.GetString("UnorderedListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string UntitledTitle {
            get {
                return ResourceManager.GetString("UntitledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch App update information failed!.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Info.
        /// </summary>
        public static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images (Don&apos;t upload illegal images).
        /// </summary>
        public static string UploadImagesTitle {
            get {
                return ResourceManager.GetString("UploadImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Local Image To Imgur（Outside PRC）.
        /// </summary>
        public static string UploadLocalImage2IMGUR {
            get {
                return ResourceManager.GetString("UploadLocalImage2IMGUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Local Image To Qiniu（PRC）.
        /// </summary>
        public static string UploadLocalImage2Qiniu {
            get {
                return ResourceManager.GetString("UploadLocalImage2Qiniu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image To .
        /// </summary>
        public static string UploadToImageStorageService {
            get {
                return ResourceManager.GetString("UploadToImageStorageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you want to save your changes?.
        /// </summary>
        public static string WhetherSaveChanges {
            get {
                return ResourceManager.GetString("WhetherSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcards.
        /// </summary>
        public static string Wildcards {
            get {
                return ResourceManager.GetString("Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string WordWrap {
            get {
                return ResourceManager.GetString("WordWrap", resourceCulture);
            }
        }
    }
}
